[package]
name = "gcn-middleend"
version.workspace = true
edition = "2024"
description = "Construction de graphe causal, détection de cycles, propagation, validation"
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
gcn-ir = { path = "../gcn-ir", version = "2.5.0" }
gcn-knowledge = { path = "../gcn-knowledge", version = "2.5.0" }
petgraph = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
smallvec = { workspace = true }
