[package]
name = "gcn-backend"
version.workspace = true
edition = "2024"
description = "Causal reasoning (Pearl), query engine, export"
license.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
gcn-ir = { path = "../gcn-ir", version = "1.0.1" }
gcn-middleend = { path = "../gcn-middleend", version = "1.0.1" }
petgraph = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
smallvec = { workspace = true }
